// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeNfiyeRoeqcZkznp7Gt2VKUjl3C8WLxE',
    appId: '1:76120671573:web:eaf27383b3d5bfcc581bdc',
    messagingSenderId: '76120671573',
    projectId: 'productivity-tracker-d2300',
    authDomain: 'productivity-tracker-d2300.firebaseapp.com',
    storageBucket: 'productivity-tracker-d2300.firebasestorage.app',
    measurementId: 'G-NL7PJNDNQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZRByYxsScTYrjg0dQReayTLupbKDgV4',
    appId: '1:76120671573:android:307827de917ba2bc581bdc',
    messagingSenderId: '76120671573',
    projectId: 'productivity-tracker-d2300',
    storageBucket: 'productivity-tracker-d2300.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH53oQIWjro_M_SKMzsVPE5XEYsKt8gOU',
    appId: '1:76120671573:ios:5bfbaf2dc6090b59581bdc',
    messagingSenderId: '76120671573',
    projectId: 'productivity-tracker-d2300',
    storageBucket: 'productivity-tracker-d2300.firebasestorage.app',
    iosClientId: '76120671573-q03dn9s1bqjihbjkc9ofrpnkpovno0uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );
}
